#! /usr/bin/env python3
from mastodon import Mastodon
from auth import akkoma_access_token
import subprocess

# set default parameters for a status
def status(*args, **kwargs):
    akko = Mastodon(api_base_url = 'https://thisis.mylegendary.quest', access_token = akkoma_access_token)
    akko.feature_set = 'pleroma'
    akko.status_post(*args, visibility='direct', language='en', content_type='text/markdown', **kwargs)

def load_check_and_execute():
    cmd = ['cat', '/proc/loadavg']
    load = subprocess.run(cmd, capture_output=True)

    if not load.stderr:
        load = load.stdout.decode('utf-8')
        load = load.split()
        load = float(load[0])
        print(f'System Load: {load}')
        if load < 1:
            print("Placeholder for running the actual script")
            #status("check, please")
    else:
        print("Couldn't get the system load")
        exit()


if __name__ == '__main__':
    load_check_and_execute()
